### ISSUE TITLE
Keep the current position when going back to the album list

### ISSUE THREAD

**Issue by naku** [sismics/music#54]
Current navigation makes it difficult to navigate in the collection:

- On the album list ("My Music") scroll down a couple of pages
- Click on an album (let's say we want to browse this album and add a few tracks)
- Hit back 
--> The album list is reloaded and the last position is lost

It would be best if there was no reloading time and the position was kept (see how it's done in Google Music for reference).

**Comment by jendib** [comment]
- Keep the album list in cache (service)
- Clean the cache when navigating to the album list if the previous page is not an album
- Use $uiAnchorScroll to keep the screen position
